[2024-12-12T09:25:17.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-12T09:25:17.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_orchestrator.dbt_run_dimensions.dbt_run_date_dim scheduled__2024-12-12T09:00:00+00:00 [queued]>
[2024-12-12T09:25:17.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_orchestrator.dbt_run_dimensions.dbt_run_date_dim scheduled__2024-12-12T09:00:00+00:00 [queued]>
[2024-12-12T09:25:17.206+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-12-12T09:25:17.224+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_dimensions.dbt_run_date_dim> on 2024-12-12 09:00:00+00:00
[2024-12-12T09:25:17.231+0000] {standard_task_runner.py:63} INFO - Started process 3370 to run task
[2024-12-12T09:25:17.233+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_orchestrator', 'dbt_run_dimensions.dbt_run_date_dim', 'scheduled__2024-12-12T09:00:00+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpg4ak9l88']
[2024-12-12T09:25:17.235+0000] {standard_task_runner.py:91} INFO - Job 445: Subtask dbt_run_dimensions.dbt_run_date_dim
[2024-12-12T09:25:17.279+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_orchestrator.dbt_run_dimensions.dbt_run_date_dim scheduled__2024-12-12T09:00:00+00:00 [running]> on host 34fdc836a0bb
[2024-12-12T09:25:17.371+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ma7moud' AIRFLOW_CTX_DAG_ID='dbt_orchestrator' AIRFLOW_CTX_TASK_ID='dbt_run_dimensions.dbt_run_date_dim' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T09:00:00+00:00'
[2024-12-12T09:25:17.372+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-12T09:25:17.383+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T09:25:17.384+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/ecommerce --models date_dim']
[2024-12-12T09:25:17.400+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T09:25:19.368+0000] {subprocess.py:93} INFO - [0m09:25:19  Running with dbt=1.8.0
[2024-12-12T09:25:19.533+0000] {subprocess.py:93} INFO - [0m09:25:19  [[33mWARNING[0m]: Deprecated functionality
[2024-12-12T09:25:19.533+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-12-12T09:25:19.534+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-12-12T09:25:19.534+0000] {subprocess.py:93} INFO - information.
[2024-12-12T09:25:19.740+0000] {subprocess.py:93} INFO - [0m09:25:19  Registered adapter: postgres=1.8.0
[2024-12-12T09:25:20.933+0000] {subprocess.py:93} INFO - [0m09:25:20  Encountered an error:
[2024-12-12T09:25:20.934+0000] {subprocess.py:93} INFO - Compilation Error
[2024-12-12T09:25:20.935+0000] {subprocess.py:93} INFO -   Model 'model.ecommerce.fact_sales' (models/olap_model/fact/fact_sales.sql) depends on a node named 'data_dim' which was not found
[2024-12-12T09:25:21.888+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-12T09:25:21.888+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-12T09:25:21.901+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-12T09:25:21.904+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_orchestrator, task_id=dbt_run_dimensions.dbt_run_date_dim, run_id=scheduled__2024-12-12T09:00:00+00:00, execution_date=20241212T090000, start_date=20241212T092517, end_date=20241212T092521
[2024-12-12T09:25:21.923+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 445 for task dbt_run_dimensions.dbt_run_date_dim (Bash command failed. The command returned a non-zero exit code 2.; 3370)
[2024-12-12T09:25:21.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-12T09:25:21.966+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T09:25:21.970+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
