[2024-12-12T09:12:44.209+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T08:45:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
